# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 8048
    v.cpus = 2
  end

   config.vm.network "private_network", ip: "192.168.56.101"

   config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true

   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     #install guest tools
     #sudo apt-get install -y linux-headers-$(uname -r) build-essential dkms
     #wget "http://download.virtualbox.org/virtualbox/5.0.26/VBoxGuestAdditions_5.0.26.iso"
     #sudo mkdir /media/VBoxGuestAdditions
     #sudo mount -o loop,ro VBoxGuestAdditions_5.0.26.iso /media/VBoxGuestAdditions
     #sudo sh /media/VBoxGuestAdditions/VBoxLinuxAdditions.run
     #rm VBoxGuestAdditions_5.0.26.iso
     #sudo umount /media/VBoxGuestAdditions
     #sudo rmdir /media/VBoxGuestAdditions
     #install volatility
     sudo apt-get install -y python2.7 python-dev python-setuptools build-essential autoconf automake autopoint libtool pkg-config git
     sudo easy_install -U pip
     sudo pip install openpyxl pycrypto distorm3
     cd /opt
     sudo git clone https://github.com/volatilityfoundation/volatility
     cd /opt/volatility
     sudo python setup.py install
     cd /opt
     #install mongo
     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
     sudo echo "deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
     sudo apt-get update
     apt-get install -y mongodb-org
     #add support for extensions
     #build libpff
     cd /opt
     git clone https://github.com/libyal/libpff.git
     cd libpff/
     ./synclibs.sh
     ./autogen.sh
     ./configure --enable-python
     make
     sudo make install
     sudo ldconfig
     cd /opt
     wget https://github.com/maxmind/libmaxminddb/releases/download/1.2.0/libmaxminddb-1.2.0.tar.gz
     tar zxvf libmaxminddb-1.2.0.tar.gz
     rm libmaxminddb-1.2.0.tar.gz
     mv libmaxminddb-1.2.0 libmaxminddb
     cd libmaxminddb/
     ./configure
     make
     make check
     sudo make install
     sudo ldconfig
     cd /opt
     wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
     gunzip GeoLite2-City.mmdb.gz
     mv GeoLite2-City.mmdb /usr/share/GeoIP
     sudo apt-get install -y libimage-exiftool-perl
     #install volutility
     cd /opt
     sudo git clone https://github.com/kevthehermit/VolUtility
     sudo chown -R vagrant:vagrant /opt/VolUtility
     cd /opt/VolUtility
     sudo pip install -r requirements.txt
     #add yara rules
     #
     #add service
     echo '#!/bin/bash' > /usr/local/bin/volutilstart.sh
     echo 'cd /opt/VolUtility' >> /usr/local/bin/volutilstart.sh
     echo '/opt/VolUtility/manage.py runserver 0.0.0.0:8765' >> /usr/local/bin/volutilstart.sh
     echo 'exit 0' >> /usr/local/bin/volutilstart.sh
     chmod +x /usr/local/bin/volutilstart.sh
     sudo apt-get install -y libpam-systemd dbus
     sudo echo "[Unit]" > /lib/systemd/system/volutility.service
     sudo echo "Description=VolUtility FrontEnd" >> /lib/systemd/system/volutility.service
     sudo echo "After=network.target" >> /lib/systemd/system/volutility.service
     sudo echo "[Service]" >> /lib/systemd/system/volutility.service
     sudo echo "User=vagrant" >> /lib/systemd/system/volutility.service
     sudo echo "WorkingDirectory=/home/vagrant" >> /lib/systemd/system/volutility.service
     sudo echo "Type=forking" >> /lib/systemd/system/volutility.service
     sudo echo "PIDFile=/run/volutility.pid" >> /lib/systemd/system/volutility.service
     sudo echo "ExecStartPre=/usr/local/bin/volutilstart.sh -t -q -g 'daemon on; master_process on;'" >> /lib/systemd/system/volutility.service
     sudo echo "ExecStart=/usr/local/bin/volutilstart.sh -g 'daemon on; master_process on;'" >> /lib/systemd/system/volutility.service
     sudo echo "ExecReload=/usr/local/bin/volutilstart.sh -g 'daemon on; master_process on;' -s reload" >> /lib/systemd/system/volutility.service
     sudo echo "ExecStop=/usr/local/bin/volutilstart.sh -s quit" >> /lib/systemd/system/volutility.service
     sudo echo "[Install]" >> /lib/systemd/system/volutility.service
     sudo echo "WantedBy=multi-user.target" >> /lib/systemd/system/volutility.service
     sudo systemctl daemon-reload
     sleep 10
     sudo systemctl enable volutility.service
     #sleep 10
     #sudo systemctl start volutility.service
     /usr/local/bin/volutilstart.sh&
   SHELL
end